version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:latest
      - image: rabbitmq:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum "ptt.gemspec" }}
      - run:
          name: Install gems dependencies
          command: bundle install --jobs=10 --path vendor/bundle
      - save_cache:
          key: bundler-cache-{{ checksum "ptt.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for RabbitMQ
          command: dockerize -wait tcp://localhost:5672 -timeout 1m
      - run:
          name: Run RSpec tests
          command: bundle exec rspec -I .
          environment:
            RABBITMQ_URL: amqp://localhost:5672

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
