#!/usr/bin/env sh
#
# Set up application for the first time after cloning, or set it back to the
# initial first unused state.
#
# Examples
#
#   script/setup
set -o errexit

cd "$(dirname "$0")/.."

echo "==> Building the Docker image…"
docker build --tag gohiring/ptt:latest .
